#数据源配置
spring:
  datasource:
    username: root
    password: azxaaa123
    url: jdbc:mysql://localhost:3306/mybatis-plus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

#日志配置
mybatis-plus:
  type-aliases-package: com.asir.mybatis_plus.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
